name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          cache-dependency-path: |
            core/go.sum

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.7
          cache: true

      - name: Get Flutter Dependency
        run: |
          flutter --version
          flutter pub get

      - name: Build
        run: dart setup.dart linux --arch amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-amd64
          path: ./dist
          if-no-files-found: error
          overwrite: true
